help([[Load environment to run prep job on WCOSS2]])
load(pathJoin("PrgEnv-intel", "None"))
load(pathJoin("hdf5", "None"))
load(pathJoin("python", "None"))
load(pathJoin("netcdf", "None"))
load(pathJoin("crtm", "None"))
prepend_path("MODULEPATH", pathJoin("/extra1/lfs/h2/emc/global/save/emc.global/git/prepobs/module"))
load(pathJoin("extra1", "None"))
load(pathJoin("extra1", "None"))
load(pathJoin("extra1", "None"))
setenv("a", "extra1")
setenv("b", "extra1")
prepend_path("MODULEPATH", pathJoin("/extra2/lfs/h2/emc/global/save/emc.global/git/prepobs/module"))
load(pathJoin("extra2", "None"))
load(pathJoin("extra2", "None"))
load(pathJoin("extra2", "None"))
setenv("a", "extra2")
setenv("b", "extra2")
load(pathJoin("prod_util", "None"))
whatis("prep run environment")
